/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as DocumentosNormativosRouteImport } from './routes/documentos-normativos'
import { Route as FonteDocumentalRouteImport } from './routes/fonte-documental'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MudancasRouteImport } from './routes/mudancas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EditaisIndexRouteImport } from './routes/editais/index'
import { Route as EditaisNovoRouteImport } from './routes/editais/novo'
import { Route as ProponentesIndexRouteImport } from './routes/proponentes/index'
import { Route as ProponentesIdRouteImport } from './routes/proponentes/$id'
import { Route as ApiInternalJobsRouteImport } from './routes/api/internal/jobs'
import { Route as EditaisEditalIdIndexRouteImport } from './routes/editais/$editalId/index'
import { Route as EditaisEditalIdAuditoriaRouteImport } from './routes/editais/$editalId/auditoria'
import { Route as EditaisEditalIdConfiguracaoRouteImport } from './routes/editais/$editalId/configuracao'
import { Route as EditaisEditalIdCustosRouteImport } from './routes/editais/$editalId/custos'
import { Route as EditaisEditalIdDocumentosNormativosRouteImport } from './routes/editais/$editalId/documentos-normativos'
import { Route as EditaisEditalIdFonteDocumentalRouteImport } from './routes/editais/$editalId/fonte-documental'
import { Route as EditaisEditalIdMudancasRouteImport } from './routes/editais/$editalId/mudancas'
import { Route as EditaisEditalIdPainelRouteImport } from './routes/editais/$editalId/painel'
import { Route as EditaisEditalIdProcessamentoRouteImport } from './routes/editais/$editalId/processamento'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google/oauth/callback'
import { Route as EditaisEditalIdProponentesIndexRouteImport } from './routes/editais/$editalId/proponentes/index'
import { Route as EditaisEditalIdProponentesApplicationIdRouteImport } from './routes/editais/$editalId/proponentes/$applicationId'
import { Route as ApiInternalJobsJobIdStagesStageRouteImport } from './routes/api/internal/jobs/$jobId/stages/$stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosNormativosRoute = DocumentosNormativosRouteImport.update({
  id: '/documentos-normativos',
  path: '/documentos-normativos',
  getParentRoute: () => rootRouteImport,
} as any)
const FonteDocumentalRoute = FonteDocumentalRouteImport.update({
  id: '/fonte-documental',
  path: '/fonte-documental',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MudancasRoute = MudancasRouteImport.update({
  id: '/mudancas',
  path: '/mudancas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisIndexRoute = EditaisIndexRouteImport.update({
  id: '/editais/',
  path: '/editais/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisNovoRoute = EditaisNovoRouteImport.update({
  id: '/editais/novo',
  path: '/editais/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentesIndexRoute = ProponentesIndexRouteImport.update({
  id: '/proponentes/',
  path: '/proponentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentesIdRoute = ProponentesIdRouteImport.update({
  id: '/proponentes/$id',
  path: '/proponentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalJobsRoute = ApiInternalJobsRouteImport.update({
  id: '/api/internal/jobs',
  path: '/api/internal/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdIndexRoute = EditaisEditalIdIndexRouteImport.update({
  id: '/editais/$editalId/',
  path: '/editais/$editalId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdAuditoriaRoute =
  EditaisEditalIdAuditoriaRouteImport.update({
    id: '/editais/$editalId/auditoria',
    path: '/editais/$editalId/auditoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditaisEditalIdConfiguracaoRoute =
  EditaisEditalIdConfiguracaoRouteImport.update({
    id: '/editais/$editalId/configuracao',
    path: '/editais/$editalId/configuracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditaisEditalIdCustosRoute = EditaisEditalIdCustosRouteImport.update({
  id: '/editais/$editalId/custos',
  path: '/editais/$editalId/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdDocumentosNormativosRoute =
  EditaisEditalIdDocumentosNormativosRouteImport.update({
    id: '/editais/$editalId/documentos-normativos',
    path: '/editais/$editalId/documentos-normativos',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditaisEditalIdFonteDocumentalRoute =
  EditaisEditalIdFonteDocumentalRouteImport.update({
    id: '/editais/$editalId/fonte-documental',
    path: '/editais/$editalId/fonte-documental',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditaisEditalIdMudancasRoute = EditaisEditalIdMudancasRouteImport.update({
  id: '/editais/$editalId/mudancas',
  path: '/editais/$editalId/mudancas',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdPainelRoute = EditaisEditalIdPainelRouteImport.update({
  id: '/editais/$editalId/painel',
  path: '/editais/$editalId/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdProcessamentoRoute =
  EditaisEditalIdProcessamentoRouteImport.update({
    id: '/editais/$editalId/processamento',
    path: '/editais/$editalId/processamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth/callback',
  path: '/api/google/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisEditalIdProponentesIndexRoute =
  EditaisEditalIdProponentesIndexRouteImport.update({
    id: '/editais/$editalId/proponentes/',
    path: '/editais/$editalId/proponentes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditaisEditalIdProponentesApplicationIdRoute =
  EditaisEditalIdProponentesApplicationIdRouteImport.update({
    id: '/editais/$editalId/proponentes/$applicationId',
    path: '/editais/$editalId/proponentes/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalJobsJobIdStagesStageRoute =
  ApiInternalJobsJobIdStagesStageRouteImport.update({
    id: '/$jobId/stages/$stage',
    path: '/$jobId/stages/$stage',
    getParentRoute: () => ApiInternalJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editais/novo': typeof EditaisNovoRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/editais/': typeof EditaisIndexRoute
  '/proponentes/': typeof ProponentesIndexRoute
  '/api/internal/jobs': typeof ApiInternalJobsRouteWithChildren
  '/editais/$editalId/auditoria': typeof EditaisEditalIdAuditoriaRoute
  '/editais/$editalId/configuracao': typeof EditaisEditalIdConfiguracaoRoute
  '/editais/$editalId/custos': typeof EditaisEditalIdCustosRoute
  '/editais/$editalId/documentos-normativos': typeof EditaisEditalIdDocumentosNormativosRoute
  '/editais/$editalId/fonte-documental': typeof EditaisEditalIdFonteDocumentalRoute
  '/editais/$editalId/mudancas': typeof EditaisEditalIdMudancasRoute
  '/editais/$editalId/painel': typeof EditaisEditalIdPainelRoute
  '/editais/$editalId/processamento': typeof EditaisEditalIdProcessamentoRoute
  '/editais/$editalId/': typeof EditaisEditalIdIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/editais/$editalId/proponentes/$applicationId': typeof EditaisEditalIdProponentesApplicationIdRoute
  '/editais/$editalId/proponentes/': typeof EditaisEditalIdProponentesIndexRoute
  '/api/internal/jobs/$jobId/stages/$stage': typeof ApiInternalJobsJobIdStagesStageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editais/novo': typeof EditaisNovoRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/editais': typeof EditaisIndexRoute
  '/proponentes': typeof ProponentesIndexRoute
  '/api/internal/jobs': typeof ApiInternalJobsRouteWithChildren
  '/editais/$editalId/auditoria': typeof EditaisEditalIdAuditoriaRoute
  '/editais/$editalId/configuracao': typeof EditaisEditalIdConfiguracaoRoute
  '/editais/$editalId/custos': typeof EditaisEditalIdCustosRoute
  '/editais/$editalId/documentos-normativos': typeof EditaisEditalIdDocumentosNormativosRoute
  '/editais/$editalId/fonte-documental': typeof EditaisEditalIdFonteDocumentalRoute
  '/editais/$editalId/mudancas': typeof EditaisEditalIdMudancasRoute
  '/editais/$editalId/painel': typeof EditaisEditalIdPainelRoute
  '/editais/$editalId/processamento': typeof EditaisEditalIdProcessamentoRoute
  '/editais/$editalId': typeof EditaisEditalIdIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/editais/$editalId/proponentes/$applicationId': typeof EditaisEditalIdProponentesApplicationIdRoute
  '/editais/$editalId/proponentes': typeof EditaisEditalIdProponentesIndexRoute
  '/api/internal/jobs/$jobId/stages/$stage': typeof ApiInternalJobsJobIdStagesStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editais/novo': typeof EditaisNovoRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/editais/': typeof EditaisIndexRoute
  '/proponentes/': typeof ProponentesIndexRoute
  '/api/internal/jobs': typeof ApiInternalJobsRouteWithChildren
  '/editais/$editalId/auditoria': typeof EditaisEditalIdAuditoriaRoute
  '/editais/$editalId/configuracao': typeof EditaisEditalIdConfiguracaoRoute
  '/editais/$editalId/custos': typeof EditaisEditalIdCustosRoute
  '/editais/$editalId/documentos-normativos': typeof EditaisEditalIdDocumentosNormativosRoute
  '/editais/$editalId/fonte-documental': typeof EditaisEditalIdFonteDocumentalRoute
  '/editais/$editalId/mudancas': typeof EditaisEditalIdMudancasRoute
  '/editais/$editalId/painel': typeof EditaisEditalIdPainelRoute
  '/editais/$editalId/processamento': typeof EditaisEditalIdProcessamentoRoute
  '/editais/$editalId/': typeof EditaisEditalIdIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/editais/$editalId/proponentes/$applicationId': typeof EditaisEditalIdProponentesApplicationIdRoute
  '/editais/$editalId/proponentes/': typeof EditaisEditalIdProponentesIndexRoute
  '/api/internal/jobs/$jobId/stages/$stage': typeof ApiInternalJobsJobIdStagesStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/editais/novo'
    | '/proponentes/$id'
    | '/editais/'
    | '/proponentes/'
    | '/api/internal/jobs'
    | '/editais/$editalId/auditoria'
    | '/editais/$editalId/configuracao'
    | '/editais/$editalId/custos'
    | '/editais/$editalId/documentos-normativos'
    | '/editais/$editalId/fonte-documental'
    | '/editais/$editalId/mudancas'
    | '/editais/$editalId/painel'
    | '/editais/$editalId/processamento'
    | '/editais/$editalId/'
    | '/api/google/oauth/callback'
    | '/editais/$editalId/proponentes/$applicationId'
    | '/editais/$editalId/proponentes/'
    | '/api/internal/jobs/$jobId/stages/$stage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/editais/novo'
    | '/proponentes/$id'
    | '/editais'
    | '/proponentes'
    | '/api/internal/jobs'
    | '/editais/$editalId/auditoria'
    | '/editais/$editalId/configuracao'
    | '/editais/$editalId/custos'
    | '/editais/$editalId/documentos-normativos'
    | '/editais/$editalId/fonte-documental'
    | '/editais/$editalId/mudancas'
    | '/editais/$editalId/painel'
    | '/editais/$editalId/processamento'
    | '/editais/$editalId'
    | '/api/google/oauth/callback'
    | '/editais/$editalId/proponentes/$applicationId'
    | '/editais/$editalId/proponentes'
    | '/api/internal/jobs/$jobId/stages/$stage'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/editais/novo'
    | '/proponentes/$id'
    | '/editais/'
    | '/proponentes/'
    | '/api/internal/jobs'
    | '/editais/$editalId/auditoria'
    | '/editais/$editalId/configuracao'
    | '/editais/$editalId/custos'
    | '/editais/$editalId/documentos-normativos'
    | '/editais/$editalId/fonte-documental'
    | '/editais/$editalId/mudancas'
    | '/editais/$editalId/painel'
    | '/editais/$editalId/processamento'
    | '/editais/$editalId/'
    | '/api/google/oauth/callback'
    | '/editais/$editalId/proponentes/$applicationId'
    | '/editais/$editalId/proponentes/'
    | '/api/internal/jobs/$jobId/stages/$stage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  DocumentosNormativosRoute: typeof DocumentosNormativosRoute
  FonteDocumentalRoute: typeof FonteDocumentalRoute
  LoginRoute: typeof LoginRoute
  MudancasRoute: typeof MudancasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EditaisNovoRoute: typeof EditaisNovoRoute
  ProponentesIdRoute: typeof ProponentesIdRoute
  EditaisIndexRoute: typeof EditaisIndexRoute
  ProponentesIndexRoute: typeof ProponentesIndexRoute
  ApiInternalJobsRoute: typeof ApiInternalJobsRouteWithChildren
  EditaisEditalIdAuditoriaRoute: typeof EditaisEditalIdAuditoriaRoute
  EditaisEditalIdConfiguracaoRoute: typeof EditaisEditalIdConfiguracaoRoute
  EditaisEditalIdCustosRoute: typeof EditaisEditalIdCustosRoute
  EditaisEditalIdDocumentosNormativosRoute: typeof EditaisEditalIdDocumentosNormativosRoute
  EditaisEditalIdFonteDocumentalRoute: typeof EditaisEditalIdFonteDocumentalRoute
  EditaisEditalIdMudancasRoute: typeof EditaisEditalIdMudancasRoute
  EditaisEditalIdPainelRoute: typeof EditaisEditalIdPainelRoute
  EditaisEditalIdProcessamentoRoute: typeof EditaisEditalIdProcessamentoRoute
  EditaisEditalIdIndexRoute: typeof EditaisEditalIdIndexRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  EditaisEditalIdProponentesApplicationIdRoute: typeof EditaisEditalIdProponentesApplicationIdRoute
  EditaisEditalIdProponentesIndexRoute: typeof EditaisEditalIdProponentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-normativos': {
      id: '/documentos-normativos'
      path: '/documentos-normativos'
      fullPath: '/documentos-normativos'
      preLoaderRoute: typeof DocumentosNormativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonte-documental': {
      id: '/fonte-documental'
      path: '/fonte-documental'
      fullPath: '/fonte-documental'
      preLoaderRoute: typeof FonteDocumentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mudancas': {
      id: '/mudancas'
      path: '/mudancas'
      fullPath: '/mudancas'
      preLoaderRoute: typeof MudancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/': {
      id: '/editais/'
      path: '/editais'
      fullPath: '/editais/'
      preLoaderRoute: typeof EditaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/novo': {
      id: '/editais/novo'
      path: '/editais/novo'
      fullPath: '/editais/novo'
      preLoaderRoute: typeof EditaisNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponentes/': {
      id: '/proponentes/'
      path: '/proponentes'
      fullPath: '/proponentes/'
      preLoaderRoute: typeof ProponentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponentes/$id': {
      id: '/proponentes/$id'
      path: '/proponentes/$id'
      fullPath: '/proponentes/$id'
      preLoaderRoute: typeof ProponentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/jobs': {
      id: '/api/internal/jobs'
      path: '/api/internal/jobs'
      fullPath: '/api/internal/jobs'
      preLoaderRoute: typeof ApiInternalJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/': {
      id: '/editais/$editalId/'
      path: '/editais/$editalId'
      fullPath: '/editais/$editalId/'
      preLoaderRoute: typeof EditaisEditalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/auditoria': {
      id: '/editais/$editalId/auditoria'
      path: '/editais/$editalId/auditoria'
      fullPath: '/editais/$editalId/auditoria'
      preLoaderRoute: typeof EditaisEditalIdAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/configuracao': {
      id: '/editais/$editalId/configuracao'
      path: '/editais/$editalId/configuracao'
      fullPath: '/editais/$editalId/configuracao'
      preLoaderRoute: typeof EditaisEditalIdConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/custos': {
      id: '/editais/$editalId/custos'
      path: '/editais/$editalId/custos'
      fullPath: '/editais/$editalId/custos'
      preLoaderRoute: typeof EditaisEditalIdCustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/documentos-normativos': {
      id: '/editais/$editalId/documentos-normativos'
      path: '/editais/$editalId/documentos-normativos'
      fullPath: '/editais/$editalId/documentos-normativos'
      preLoaderRoute: typeof EditaisEditalIdDocumentosNormativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/fonte-documental': {
      id: '/editais/$editalId/fonte-documental'
      path: '/editais/$editalId/fonte-documental'
      fullPath: '/editais/$editalId/fonte-documental'
      preLoaderRoute: typeof EditaisEditalIdFonteDocumentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/mudancas': {
      id: '/editais/$editalId/mudancas'
      path: '/editais/$editalId/mudancas'
      fullPath: '/editais/$editalId/mudancas'
      preLoaderRoute: typeof EditaisEditalIdMudancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/painel': {
      id: '/editais/$editalId/painel'
      path: '/editais/$editalId/painel'
      fullPath: '/editais/$editalId/painel'
      preLoaderRoute: typeof EditaisEditalIdPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/processamento': {
      id: '/editais/$editalId/processamento'
      path: '/editais/$editalId/processamento'
      fullPath: '/editais/$editalId/processamento'
      preLoaderRoute: typeof EditaisEditalIdProcessamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/callback': {
      id: '/api/google/oauth/callback'
      path: '/api/google/oauth/callback'
      fullPath: '/api/google/oauth/callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/proponentes/': {
      id: '/editais/$editalId/proponentes/'
      path: '/editais/$editalId/proponentes'
      fullPath: '/editais/$editalId/proponentes/'
      preLoaderRoute: typeof EditaisEditalIdProponentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$editalId/proponentes/$applicationId': {
      id: '/editais/$editalId/proponentes/$applicationId'
      path: '/editais/$editalId/proponentes/$applicationId'
      fullPath: '/editais/$editalId/proponentes/$applicationId'
      preLoaderRoute: typeof EditaisEditalIdProponentesApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/jobs/$jobId/stages/$stage': {
      id: '/api/internal/jobs/$jobId/stages/$stage'
      path: '/$jobId/stages/$stage'
      fullPath: '/api/internal/jobs/$jobId/stages/$stage'
      preLoaderRoute: typeof ApiInternalJobsJobIdStagesStageRouteImport
      parentRoute: typeof ApiInternalJobsRoute
    }
  }
}

interface ApiInternalJobsRouteChildren {
  ApiInternalJobsJobIdStagesStageRoute: typeof ApiInternalJobsJobIdStagesStageRoute
}

const ApiInternalJobsRouteChildren: ApiInternalJobsRouteChildren = {
  ApiInternalJobsJobIdStagesStageRoute: ApiInternalJobsJobIdStagesStageRoute,
}

const ApiInternalJobsRouteWithChildren = ApiInternalJobsRoute._addFileChildren(
  ApiInternalJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  DocumentosNormativosRoute: DocumentosNormativosRoute,
  FonteDocumentalRoute: FonteDocumentalRoute,
  LoginRoute: LoginRoute,
  MudancasRoute: MudancasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EditaisNovoRoute: EditaisNovoRoute,
  ProponentesIdRoute: ProponentesIdRoute,
  EditaisIndexRoute: EditaisIndexRoute,
  ProponentesIndexRoute: ProponentesIndexRoute,
  ApiInternalJobsRoute: ApiInternalJobsRouteWithChildren,
  EditaisEditalIdAuditoriaRoute: EditaisEditalIdAuditoriaRoute,
  EditaisEditalIdConfiguracaoRoute: EditaisEditalIdConfiguracaoRoute,
  EditaisEditalIdCustosRoute: EditaisEditalIdCustosRoute,
  EditaisEditalIdDocumentosNormativosRoute:
    EditaisEditalIdDocumentosNormativosRoute,
  EditaisEditalIdFonteDocumentalRoute: EditaisEditalIdFonteDocumentalRoute,
  EditaisEditalIdMudancasRoute: EditaisEditalIdMudancasRoute,
  EditaisEditalIdPainelRoute: EditaisEditalIdPainelRoute,
  EditaisEditalIdProcessamentoRoute: EditaisEditalIdProcessamentoRoute,
  EditaisEditalIdIndexRoute: EditaisEditalIdIndexRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  EditaisEditalIdProponentesApplicationIdRoute:
    EditaisEditalIdProponentesApplicationIdRoute,
  EditaisEditalIdProponentesIndexRoute: EditaisEditalIdProponentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
