/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MudancasRouteImport } from './routes/mudancas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FonteDocumentalRouteImport } from './routes/fonte-documental'
import { Route as DocumentosNormativosRouteImport } from './routes/documentos-normativos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProponentesIndexRouteImport } from './routes/proponentes/index'
import { Route as ProponentesIdRouteImport } from './routes/proponentes/$id'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google/oauth/callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MudancasRoute = MudancasRouteImport.update({
  id: '/mudancas',
  path: '/mudancas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FonteDocumentalRoute = FonteDocumentalRouteImport.update({
  id: '/fonte-documental',
  path: '/fonte-documental',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosNormativosRoute = DocumentosNormativosRouteImport.update({
  id: '/documentos-normativos',
  path: '/documentos-normativos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentesIndexRoute = ProponentesIndexRouteImport.update({
  id: '/proponentes/',
  path: '/proponentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentesIdRoute = ProponentesIdRouteImport.update({
  id: '/proponentes/$id',
  path: '/proponentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth/callback',
  path: '/api/google/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/proponentes/': typeof ProponentesIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/proponentes': typeof ProponentesIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/documentos-normativos': typeof DocumentosNormativosRoute
  '/fonte-documental': typeof FonteDocumentalRoute
  '/login': typeof LoginRoute
  '/mudancas': typeof MudancasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/proponentes/$id': typeof ProponentesIdRoute
  '/proponentes/': typeof ProponentesIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/proponentes/$id'
    | '/proponentes/'
    | '/api/google/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/proponentes/$id'
    | '/proponentes'
    | '/api/google/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/documentos-normativos'
    | '/fonte-documental'
    | '/login'
    | '/mudancas'
    | '/reset-password'
    | '/proponentes/$id'
    | '/proponentes/'
    | '/api/google/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  DocumentosNormativosRoute: typeof DocumentosNormativosRoute
  FonteDocumentalRoute: typeof FonteDocumentalRoute
  LoginRoute: typeof LoginRoute
  MudancasRoute: typeof MudancasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProponentesIdRoute: typeof ProponentesIdRoute
  ProponentesIndexRoute: typeof ProponentesIndexRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mudancas': {
      id: '/mudancas'
      path: '/mudancas'
      fullPath: '/mudancas'
      preLoaderRoute: typeof MudancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonte-documental': {
      id: '/fonte-documental'
      path: '/fonte-documental'
      fullPath: '/fonte-documental'
      preLoaderRoute: typeof FonteDocumentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-normativos': {
      id: '/documentos-normativos'
      path: '/documentos-normativos'
      fullPath: '/documentos-normativos'
      preLoaderRoute: typeof DocumentosNormativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponentes/': {
      id: '/proponentes/'
      path: '/proponentes'
      fullPath: '/proponentes/'
      preLoaderRoute: typeof ProponentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponentes/$id': {
      id: '/proponentes/$id'
      path: '/proponentes/$id'
      fullPath: '/proponentes/$id'
      preLoaderRoute: typeof ProponentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/callback': {
      id: '/api/google/oauth/callback'
      path: '/api/google/oauth/callback'
      fullPath: '/api/google/oauth/callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  DocumentosNormativosRoute: DocumentosNormativosRoute,
  FonteDocumentalRoute: FonteDocumentalRoute,
  LoginRoute: LoginRoute,
  MudancasRoute: MudancasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProponentesIdRoute: ProponentesIdRoute,
  ProponentesIndexRoute: ProponentesIndexRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
